# vim:foldmethod=marker:
---
# Before anything else, make sure the system is up to date.
# TODO: On secure boot systems this will break kernel updates.
# - name: Upgrade System
#   hosts: all
#   become: yes
#   tasks:
#     - name: Pacman -Syu
#       pacman:
#         update_cache: yes
#         upgrade: yes
# COMMON TO ALL HOSTS {{{
- name: Baseline
  hosts: all
  import_tasks: 'base.yml'
# }}}
# ANSIBLE-PULL {{{
- name: 'Enable ansible-pull periodically'
  become: true
  hosts: pull_config
  vars:
    ansible_pull_dir: '/var/tmp/ansible'
    ansible_pull_url: 'https://github.com/alxbl/config'
    ansible_pull_hosts: 'hosts'
    ansible_pull_playbook: 'playbook.yml'
    ansible_pull_log_file: '/var/tmp/ansible/lastrun.log'
  tasks:
    - name: Configure ansible service
      template:
        src: files/common/ansibled.service.j2
        dest: /usr/lib/systemd/system/ansibled.service
        owner: root
        group: root
        mode: 0644
    - name: Configure ansible timer
      block:
        - name: Ansible timer
          copy:
            src: files/common/ansibled.timer
            dest: /usr/lib/systemd/system/ansibled.timer
            owner: root
            group: root
            mode: 0644
        - name: Enable timer
          service:
            name: ansibled.timer
            enabled: true
            state: started
# }}}
# ROLES {{{
################################################################################
- hosts: hypervisor
  become: true
  roles:
    - hypervisor

- hosts: workstation
  become: true
  roles:
    - dev

- hosts: gui
  become: true
  roles:
    - gui

# }}}
# PER-HOST SPECIFIC TASKS (optional) {{{
################################################################################
- name: Host-specific tasks
  hosts: all
  tasks:
    - name: Load task list
      include_tasks: '{{ item }}'
      with_first_found:
        - files:
          - 'roles/{{ inventory_hostname }}.yml'
          skip: true
# }}}
